simplify shell prompt

diff --git a/dot_bashrc b/dot_bashrc
--- a/dot_bashrc
+++ b/dot_bashrc
@@ -94,37 +94,26 @@ fi
 
 alias cz='chezmoi'
 alias v='vscli open'
-alias dp='devpod'
 
-if [ -n "${FLOX_ENV}${DEVBOX_WD}${DEVPOD}${REMOTE_CONTAINERS}" ]; then
-  function _omb_theme_PROMPT_COMMAND() {
-      # This needs to be first to save last command return code
-      local RC="$?"
+function _omb_theme_PROMPT_COMMAND() {
+    # This needs to be first to save last command return code
+    local RC="$?"
 
-      local hostname="${_omb_prompt_bold_gray}\u@\h"
-      local venv
+    local hostname="${_omb_prompt_bold_gray}\u@${_omb_prompt_bold_magenta}\h"
+    local venv
 
-      if [ -n "${FLOX_ENV}${DEVBOX_WD}" ]; then
-        venv="👻 "
-      elif [ -n "${DEVPOD}${REMOTE_CONTAINERS}" ]; then
-        venv="📦 "
-      else
-        venv="📡 "
-      fi
+    # Set return status color
+    if [[ ${RC} == 0 ]]; then
+        ret_status="${_omb_prompt_bold_green}"
+    else
+        ret_status="${_omb_prompt_bold_brown}"
+    fi
 
-      # Set return status color
-      if [[ ${RC} == 0 ]]; then
-          ret_status="${_omb_prompt_bold_green}"
-      else
-          ret_status="${_omb_prompt_bold_brown}"
-      fi
+    # Append new history lines to history file
+    history -a
 
-      # Append new history lines to history file
-      history -a
-
-      PS1="$(clock_prompt)$venv${hostname} ${_omb_prompt_bold_teal}\W $(scm_prompt_char_info)${ret_status}→ ${_omb_prompt_normal}"
+    PS1="$(clock_prompt)${hostname} ${_omb_prompt_bold_teal}\W $(scm_prompt_char_info)${ret_status}→ ${_omb_prompt_normal}"
   }
-fi
 
 if [ -f ~/Documents/CloudBox/keys/ansible-vault-password ]; then
   export ANSIBLE_VAULT_PASSWORD_FILE=$HOME/Documents/CloudBox/keys/ansible-vault-password
